[Draft]: Adds Reserved IP support.
crossplane-contrib/provider-civo pull request #28
Opened 2022-07-14 15:26 UTC by haardikdharma10

### Description of your changes

Adds Reserved IP support.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

2022-07-14 15:30 UTC, RealHarshThakur commented on apis/civo/instance/v1alpha1/types.go
> +	ReservedIP string `json:"reserved_ip,omitempty"`
```suggestion
       // Name of the CivoIP custom resource
	ReservedIP string `json:"reserved_ip,omitempty"`
```

2022-07-14 15:54 UTC, RealHarshThakur commented on internal/controller/civoinstance/civoinstance.go
> +			return managed.ExternalCreation{}, err
If it's empty, we have to unassign any reserved IP. Like we do in CCM

2022-07-15 08:34 UTC, RealHarshThakur commented on internal/controller/civoip/civoip.go
> +
You should still get the object, update the status with latest information

2022-07-15 08:35 UTC, RealHarshThakur commented on internal/controller/civoip/civoip.go
> +	if civoIP.IP != "" {
Status should be updated with latest information

2022-07-19 01:25 UTC, RealHarshThakur commented on pkg/civocli/cli.go
> +func (c *CivoClient) ListIPs() (*civogo.PaginatedIPs, error) {
I don't think List, Assign,Unassign and Delete methods here are required. They feel like duplicating the calls from Civo Go client

2022-07-25 23:36 UTC, RealHarshThakur requested changes

2022-07-25 23:36 UTC, RealHarshThakur commented on e2e/ip_test.go
> +	ip := &civoip.CivoIP{
Can we have the IP creation in a separate method which checks if the IP already exists with the name and doesn't recreate it if not needed?

2022-07-25 23:36 UTC, RealHarshThakur commented on e2e/ip_test.go
> +				Hostname:  "e2e-test-instance",
We're supposed to pass in the name of the reserved IP here

2022-07-25 23:36 UTC, RealHarshThakur commented on e2e/ip_test.go
> +		err = e2eTest.tenantClient.Get(context.TODO(), client.ObjectKeyFromObject(instance), instance)
We don't need this, this should be hard coded during instance creation

2022-07-26 08:06 UTC, RealHarshThakur commented on internal/controller/civoinstance/civoinstance.go
> +	err = e.kube.Get(ctx, types.NamespacedName{Name: civoInstance.ReservedIP}, ip)
We should wrap this in an if block which checks if civoinstance.ReservedIP is not empty

2022-07-26 08:07 UTC, RealHarshThakur commented on internal/controller/civoinstance/civoinstance.go
> +	err = e.kube.Get(ctx, types.NamespacedName{Name: civoInstance.ReservedIP}, ip)
Can you also write an e2e test which creates an instance without reserved IP?

2022-09-29 05:45 UTC, RealHarshThakur commented on e2e/ip_test.go
> +
Can we also have following tests please?
* Unassignment of reserved IP: removing the `ReservedIP` field from instance spec should unassign the reserved IP. 
* Deletion of reserved IP: Deleting the reserved IP after creation. Just to cover entire lifecycle.

2022-09-29 05:46 UTC, RealHarshThakur commented on examples/civo/instance/instance-nossh.yaml
> +    reserved_ip: test-crossplane-ip
I think we should create a different example with a filename `instance-reservedIP` for this example

2022-09-29 05:47 UTC, RealHarshThakur commented on examples/civo/provider/provider.yaml
> +  credentials: <replace with base64 encoded Civo API KEY>
This should stay commented

2022-09-29 10:36 UTC, closed without merging

2022-10-03 09:58 UTC, satakshigarg commented on examples/civo/instance/instance-nossh.yaml
> +    reserved_ip: test-crossplane-ip
@RealHarshThakur shall I rename this instance-nossh.yaml to instance-reservedIP or create a new example file ?