changing api types to provide cluster status
crossplane-contrib/provider-civo pull request #4
Opened 2021-07-27 15:40 UTC by AnaisUrlichs

Changes API types to show the status message and further information on the newly create civokubernetes resource
![clusterstatus](https://user-images.githubusercontent.com/33576047/127184214-716eec25-a1ab-4b5f-a2f1-0480916a3440.PNG)

2021-07-27 16:28 UTC, hasheddan requested changes

2021-07-27 16:28 UTC, hasheddan commented on package/crds/civo.crossplane.io_providerconfigs.yaml
>  apiVersion: apiextensions.k8s.io/v1
@AnaisUrlichs these are stripped off when we run `make generate` but it looks like CI got confused here and didn't run -- would you mind running `make generate` and then force pushing? :)

2021-07-27 16:52 UTC, AnaisUrlichs commented on package/crds/civo.crossplane.io_providerconfigs.yaml
>  apiVersion: apiextensions.k8s.io/v1
Make generate throws errors when I run it locally 🤔 

`Makefile:6: build/makelib/common.mk: No such file or directory
make: *** No rule to make target 'build/makelib/common.mk'.  Stop.`

2021-07-27 16:53 UTC, hasheddan commented on package/crds/civo.crossplane.io_providerconfigs.yaml
>  apiVersion: apiextensions.k8s.io/v1
@AnaisUrlichs try running `git submodule update --init` first 👍🏻

2021-07-28 02:25 UTC, hasheddan approved these changes

2021-07-28 07:31 UTC, merged