Added Support for Civo Object Store
crossplane-contrib/provider-civo pull request #54
Opened 2024-03-07 09:28 UTC by uzaxirr

### Description of your changes

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2024-03-11 08:55 UTC, RealHarshThakur commented on internal/controller/civoobjectstore/civoobjectstore.go
> +		_, err = e.Update(ctx, mg)
we should only update if the value of secret's don't match the access key id , etc we got from civo api.

2024-03-11 08:58 UTC, RealHarshThakur commented on internal/controller/civoobjectstore/civoobjectstore.go
> +	if err != nil {
this function isn't idempotent, is it? If the resource exists, it'll keep going into an error state.

2024-03-11 09:00 UTC, RealHarshThakur commented on internal/controller/civoobjectstore/civoobjectstore.go
> +	err = e.civoClient.UpdateObjectStore(objectStore.ID, os.Spec.Size)
we should not always call civo api. We should first check if the desired size matches the requested size. Network calls are expensive, we should make as few as possible.

2024-03-11 09:01 UTC, RealHarshThakur commented on internal/controller/civoobjectstore/civoobjectstore.go
> +	if err != nil {
this function is not idempotent. If the resource does not exist, we should consider it deleted.

2024-03-11 10:04 UTC, uzaxirr commented on internal/controller/civoobjectstore/civoobjectstore.go
> +	err = e.civoClient.UpdateObjectStore(objectStore.ID, os.Spec.Size)
https://github.com/crossplane-contrib/provider-civo/pull/54/commits/89d911403c942ed23832fad5a58c7135346d0b55

2024-03-11 11:41 UTC, RealHarshThakur requested changes

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/doc.go
> +Copyright 2020 The Crossplane Authors.
Copyright 2024?

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	Name string `json:"Name"`
Can we drop the Name from here? We have it in the spec, I don't see why we should have it in status again.

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	MaxSize int64 `json:"Size"`
Can we have all the JSON fields start with lower case characters? It looks inconsistent all over  right now

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	Status string `json:"status,omitempty"`
Can we drop the Status field and use Conditions? https://heidloff.net/article/storing-state-status-kubernetes-resources-conditions-operators-go/

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	MaxSize int64 `json:"Size"`
Also, can we call this as `UsedCapacity` with type string instead? This way we can mention the units in MB, GB, etc.

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	ConnectionDetails CivoObjectStoreConnectionDetails `json:"connectionDetails"`
Missing description on field. These fields is the only help menu we provide to the user. When they do a kubectl explain  they can view the description we give. We should mention that this is going to be the place where we store access key and secret access key.

2024-03-11 11:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.maxSize",description="Size of the Bucket in GB"
I think it might be better to have used capacity here rather than requested.

2024-03-11 18:25 UTC, uzaxirr commented on apis/civo/objectstore/v1alpha1/types.go
> +// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.maxSize",description="Size of the Bucket in GB"
Again how should we get the used capacity?

2024-03-12 04:31 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	MaxSize int64 `json:"Size"`
There's an endpoint at `/v2/objectstore/id/stats`.

2024-03-12 04:31 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.maxSize",description="Size of the Bucket in GB"
There's an endpoint at /v2/objectstore/id/stats.

2024-03-12 04:32 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	MaxSize int `json:"size,omitempty"`
the json tag is still size, shall we rename that to `maxSize`?

2024-03-12 04:35 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	Conditions          []metav1.Condition          `json:"conditions"`
Looks good. Can we now create a special type for condition types i.e `type ConditionType string` and list all the condition types we anticipate (`ObjectStoreProvisioned`,etc)?

2024-03-13 17:42 UTC, uzaxirr commented on apis/civo/objectstore/v1alpha1/types.go
> +	Conditions          []metav1.Condition          `json:"conditions"`
something like this? https://github.com/crossplane-contrib/provider-civo/pull/54/commits/9c00feae8bdd6465a34c449c8b6cbc8147c1e806

2024-03-14 06:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	ObjectStoreProvisioned ConditionType = "ObjectStoreProvisioned"
I think we only need Provisioned . If provisioning fails, we set the condition to false and mention the reason within metav1.Condition.

2024-03-14 06:41 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	ObjectStoreProvisioned ConditionType = "ObjectStoreProvisioned"
Can you also add comments on top of these to explain what state they're representing?

2024-03-14 06:42 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	Status CivoObjectStoreStatus `json:"status,omitempty"`
Drop this field.

2024-03-14 06:42 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +	Region string `json:"region,omitempty"`
do we really need this? Isn't it implicit since they've the provider configured to single region?

2024-03-14 06:44 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.maxSize",description="Size of the Bucket in GB"
Can you check if we can display a percentage here? Would be nice to show utilised percentage. 
Basically, `.status.usedCapacity/.status.maxSize*100`

2024-03-14 06:45 UTC, RealHarshThakur commented on apis/civo/objectstore/v1alpha1/types.go
> +// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.maxSize",description="Size of the Bucket in GB"
If not, rather than displaying usedCapacity, let's have `utilisedPercentage` in status and drop `usedCapacity`

2024-03-26 09:58 UTC, closed without merging